### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by luzpaz**
Tweeked and elaborated README.md

### CODE REVIEW

**Comment by luzpaz** [comment]
@microelly2 thoughts?

**Comment by luzpaz** [comment]
@microelly2 ping

**Comment by luzpaz** [comment]
bump

**Comment by microelly2** [comment]
sorry, i have not seen this request for weeks.

**Comment by luzpaz** [comment]
@microelly2 so you're not going to merge any of the proposed changes ?

**Pull request closed without merging**
